### ISSUE TITLE
how to .config file edit

### ISSUE THREAD

**Issue by voidstring** [sipeed/maix_train#9]
![image](https://user-images.githubusercontent.com/43322788/118028157-6efed880-b36b-11eb-84c1-9e4d96611cb8.png)
I am getting such an error
![1234](https://user-images.githubusercontent.com/43322788/118028497-cef57f00-b36b-11eb-866c-bf7ce6b30fde.jpg)

What am I supposed to do. Can you help me?

**Comment by voidstring** [comment]
![130a537f-58fd-4d55-bf61-54400646240c](https://user-images.githubusercontent.com/43322788/118111748-cdb86680-b3ec-11eb-96bf-2bce868d6eb2.jpg)
the whole error

**Comment by Neutree** [comment]
![image](https://user-images.githubusercontent.com/8625829/118115029-f9eadc00-b41a-11eb-8c9e-522cf6a6608e.png)

**Comment by voidstring** [comment]
thank
